10 PRINT "<HTML>"
20 PRINT "  <HEAD>"
30 PRINT "    <TITLE>About the Commodore 64 Web Server</TITLE>"
40 PRINT "  </HEAD>"
50 PRINT "  <BODY>"
60 PRINT "    <H1>About the 64 Web Server running on AWS Lambda</H1>"
70 PRINT "    Coming soon :)"
100 PRINT "    <HR />"
110 PRINT "      <A HREF='/'>HOME</A> |"
120 PRINT "      <A HREF='/about'>About this project</A>"
200 PRINT "    <HR />"
210 PRINT "    (c) 2022 Dennis Vink, Binx.io"
220 PRINT "  </BODY>"
230 PRINT "</HTML>"
