10 PRINT "<HTML>"
20 PRINT "  <HEAD>"
30 PRINT "    <TITLE>About the Commodore 64 Web Server</TITLE>"
40 PRINT "  </HEAD>"
50 PRINT "  <BODY>"
60 PRINT "    <H1>About the 64 Web Server running on AWS Lambda</H1>"
70 PRINT "   <HR />Coming :)"
80 PRINT "  </BODY>"
90 PRINT "</HTML>"
