10 PRINT "<HTML>"
20 PRINT "  <HEAD>"
30 PRINT "    <TITLE>About the Commodore 64 Web Server</TITLE>"
40 PRINT "  </HEAD>"
50 PRINT "  <BODY>"
60 PRINT "    <H1>About the Commodore 64 Web Server running on AWS Lambda</H1>"
70 PRINT "    <P>This project was created as an homage to the C64. It showcases "
71 PRINT "       the relevance of the C64 in contemporary times, in a day and "
72 PRINT "       age of cloud technology."
73 PRINT "    </P>"
74 PRINT "    <P>This web page was rendered by cbmbasic, a C64 runtime created "
75 PRINT "       by Michael Steil and James Abbatiello.</P>"
76 PRINT "    <P>The source code for the serverless Commmodore 64 Web Server is "
77 PRINT "       available on Github at:</P>"
78 PRINT "    <P><A HREF='https://github.com/dennisvink/c64-serverless-webserver'>"
79 PRINT "      https://github.com/dennisvink/c64-serverless-webserver</A>"
80 PRINT "    </P>"
100 PRINT "    <HR />"
110 PRINT "      <A HREF='/'>HOME</A> |"
115 PRINT "      <A HREF='/lyrics'>Random Goth Lyrics</A> |"
120 PRINT "      <A HREF='/about'>About this project</A>"
200 PRINT "    <HR />"
210 PRINT "    (c) 2022 Dennis Vink, Binx.io"
220 PRINT "  </BODY>"
230 PRINT "</HTML>"
