10 PRINT "<HTML>"
20 PRINT "  <HEAD>"
30 PRINT "    <TITLE>Serverless Commodore 64 Web Server on AWS Lambda</TITLE>"
40 PRINT "  </HEAD>"
50 PRINT "  <BODY>"
60 PRINT "    <H1>Commodore 64 Web Server</H1>"
61 PRINT "    <P>Welcome to this very simple Commodore 64 Web Server!</P>"
62 PRINT "    <P>You can find the repository at:</P>"
63 PRINT "    <P><A HREF='https://github.com/dennisvink/c64-serverless-webserver'>"
64 PRINT "      https://github.com/dennisvink/c64-serverless-webserver</A>"
65 PRINT "    </P>"
100 PRINT "    <HR />"
110 PRINT "      <A HREF='/'>HOME</A> |"
115 PRINT "      <A HREF='/lyrics'>Random Goth Lyrics</A> |"
120 PRINT "      <A HREF='/about'>About this project</A>"
200 PRINT "    <HR />"
210 PRINT "    (c) 2022 Dennis Vink, Binx.io"
220 PRINT "  </BODY>"
230 PRINT "</HTML>"
