10 PRINT "<HTML>"
20 PRINT "  <HEAD>"
30 PRINT "    <TITLE>Serverless Commodore 64 Web Server on AWS Lambda</TITLE>"
40 PRINT "  </HEAD>"
50 PRINT "  <BODY>"
60 PRINT "    <H1>Commodore 64 Web Server</H1>"
100 PRINT "    <HR />"
110 PRINT "      <A HREF='/'>HOME</A> |"
120 PRINT "      <A HREF='/about'>About this project</A>"
200 PRINT "    <HR />"
210 PRINT "    (c) 2022 Dennis Vink, Binx.io"
220 PRINT "  </BODY>"
230 PRINT "</HTML>"
