10 PRINT "<HTML>"
20 PRINT "  <HEAD>"
30 PRINT "    <TITLE>Serverless Commodore 64 Web Server on AWS Lambda</TITLE>"
40 PRINT "  </HEAD>"
50 PRINT "  <BODY>"
60 PRINT "    <H1>Commodore 64 Web Server</H1><HR />"
70 PRINT "    (c) 2022 Dennis Vink, Binx.io"
80 PRINT "  </BODY>"
90 PRINT "</HTML>"
